"use client";

import type { AuditResult } from "@/types/audit";
import { ReportHeader } from "@/components/report/ReportHeader";
import { PerformanceOverview } from "@/components/report/PerformanceOverview";
import { WhySlow } from "@/components/report/WhySlow";
import { PriorityFixes } from "@/components/report/PriorityFixes";
import { Waterfall } from "@/components/waterfall/Waterfall";
import { ResourceTable } from "@/components/resources/ResourceTable";
import { ThirdPartyPanel } from "@/components/report/ThirdPartyPanel";
import { CacheAndCompression, TechStack } from "@/components/report/CacheAndTech";

export function ReportView({ result, onRescan }: { result: AuditResult; onRescan: () => void }) {
  return (
    <div className="min-h-screen">
      <ReportHeader result={result} onRescan={onRescan} />

      <main className="mx-auto max-w-5xl space-y-14 px-6 py-10">
        <section className="animate-fade-in-up">
          <PerformanceOverview result={result} />
        </section>

        <section className="animate-fade-in-up">
          <WhySlow result={result} />
        </section>

        <section className="animate-fade-in-up">
          <PriorityFixes issues={result.issues} />
        </section>

        <section className="animate-fade-in-up">
          <Waterfall requests={result.waterfall} />
        </section>

        <section className="animate-fade-in-up">
          <ResourceTable resources={result.resources} />
        </section>

        <section className="animate-fade-in-up">
          <ThirdPartyPanel domains={result.thirdParty} />
        </section>

        <section className="grid animate-fade-in-up grid-cols-1 gap-10 lg:grid-cols-2">
          <CacheAndCompression resources={result.resources} />
          <TechStack technologies={result.technologies} />
        </section>
      </main>

      <footer className="border-t border-border-subtle py-8 text-center text-xs text-foreground/35">
        Generated by AUDIT · Results are kept for 30 minutes and not stored permanently.
      </footer>
    </div>
  );
}
